<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;

class AutoGenerated
{
    public function getNextNo(string $autoFieldNumber, string $beginningValue, string $tableName): string
    {
        date_default_timezone_set("Asia/Singapore");
        $currentDate = date("ymd");
        $newNoPrefix = $beginningValue . $currentDate . "-";

        $tmpNo = substr($currentDate, 0, 4);

        $count = DB::table($tableName)
            ->where($autoFieldNumber, 'like', $beginningValue . $tmpNo . '%')
            ->distinct($autoFieldNumber)
            ->count($autoFieldNumber);

        $maxNo = $count > 0 ? $count + 1 : 1;

        if ($maxNo < 10) {
            $newNum = "00" . $maxNo;
        } elseif ($maxNo < 100) {
            $newNum = "0" . $maxNo;
        } else {
            $newNum = (string)$maxNo;
        }

        return $newNoPrefix . $newNum;
    }
}
